// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enenpgtktplylpiiuctl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuZW5wZ3RrdHBseWxwaWl1Y3RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MjE2ODMsImV4cCI6MjA3MTM5NzY4M30.u566kIUZHfHsaN9yBem-jTKiczGN-pvjXUuzD0O9hmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});